### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by JohnKhandygo** [leonid135/orientedGraph#1]
- [x] Добавьте .gitignore файл. В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).
- [x] Добавьте javadoc к разработанным классам. В javadoc должно быть дано краткое описание логики работы программы, ее входных/выходных параметров и исключений (если есть) на английском языке. Особое внимание стоит уделить краевым случаям работы методов. Методы, наследованные от `Object`, а также getter'ы/setter'ы и тестовые методы, можно не описывать.
- [ ] В java проектах принято файлы исходного кода организовать в определнной структуре папок. Одна из наиболее распространенных структур папок описана [здесь](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) или [здесь](https://stackoverflow.com/questions/41638654/java-project-folder-structure-in-intellij-idea). 
- [x] В java принято орагнизовывать классы в пакеты. Общепринятые правила именования пакетов см. [здесь](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html). Понятно, что у Вас скорее всего нет никакого сайта. В этом случае можно его придумать или взять название орагнизации, в рамках которой делается проект. Например, `org.spbstu.your_surname`.
- [x] В исходном коде программы встречаются разночтения стиля кодирования/форматирования. В качестве референсного стиля кодирования можно использовать [google java style guide](https://google.github.io/styleguide/javaguide.html).
- [x] В java классы, включая классы, содержащие тесты принято именовать в [UpperCamelCase](http://wiki.c2.com/?UpperCamelCase).
- [x] В Вашем проекте не должно быть лишних файлов. Так, например, не понятно, зачем Вам класс `Application`.
- [x] Методы, изменяющие граф, не дают возможности программно понять, была ли в действительности совершена операция или такой вершины/ребра просто не было в графе. 
- [x] У Вас в коде повсеместно встречается сравнение строк с использованием `==`. Так нельзя сравнивать объекты (и строки в том числе). Подробности см. [здесь](https://stackoverflow.com/questions/7375427/comparing-two-identical-strings-with-returns-false).
- [x] Подумайте, могут ли методы `getVertices` и `getEdges` куак-то "сломать" Ваш класс. Если да, то как?
- [x] Метод `equals` с логической точки зрения реализован некорректно. 
- [x] В тестах у Вас достаточно много копипаста (например, Вы часто создаете графы с одинаковым набором вершин). Повторяющийся код стоит выносить в отдельные функции. Это позволяет сделать код более читаемым, а также сократить его запись.
- [x] Не покрыты тестами сценарии использвания графа в случае, когда искомой вершины/ребра не существует.
- [x] Тестовые методы `outputEdges` и `inputEdges` не проверяют работу соответствующих функций.

**Comment by JohnKhandygo** [comment]
Не вижу исправлений. Если есть какие-то вопросы, пишите сюда. Если для Вас это слишком сложно, давайте определим, что достаточно сделать на 3. 

В любом случае, напишите сюда, когда задание будет готово к повторной проверке.

**Comment by leonid135** [comment]
Прошу прощения за задержку .
Задание готово к повторной проверке .

**Comment by leonid135** [comment]
john

**Comment by JohnKhandygo** [comment]
Все, что не отмечено галочками из предыдущих комментариев актуально. 

Касательно .gitignore: не все project specific файлы включены в .gitignore. Кроме того, название .iml файла зависит от того, как называется сам проект. Например, по умолчанию idea делает название проекта равным названию папки, в которой он находится, а поскольку Ваш репозиторий называется orientedGraph, то также называется и папка, в которую он попадает при слонирование. 
![2018-04-08 14_30_35-orientedgraph c__projects_study_leonid135_orientedgraph - intellij idea](https://user-images.githubusercontent.com/2545754/38466922-757558d6-3b39-11e8-8ac2-43ae1821ac7b.png)
Также необходимо удалить все игнорируемые файлы из репозитория. Инструкцию смотри [здесь](https://gist.github.com/scy/6636390).

**Comment by leonid135** [comment]
Все замечания исправлены .
Могу я получить второе задание ?

**Comment by leonid135** [comment]
John

**Comment by JohnKhandygo** [comment]
Все замечательно, есть только одно замечание: src/main/java и src/test/java --- это обычные директории, внутри которых уже располагаются пакеты приложения (`org.spbstu.ziminlo` в Вашем случае).

Для того, чтобы исправить необходимо сделать следующее:
1. В idea перейти по file -> project structure -> modules (ctrl + alt + shift + S)
2. Убрать маркер sources с папки src. Для этого надо просто щелкнуть по кнопке sources (иконка с синей папкой) пока выбрана папка src либо правой кнопкой по src и выбрать sources.
3. Пометить директорию src/main/java как sources.
4. Пометить директорию src/test/java как tests.
5. Нажать кнопку ОК.
6. Во всех файлах исходного кода исправить название пакета на валидное. 

После исправления этого замечания получаете оценку 5, следующее задание сейчас вышлю.

**Comment by leonid135** [comment]
Спасибо !
Все исправил
