### ISSUE TITLE
Task 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [leonid135/orientedGraph#2]
Вам осталось исправить совсем чуть-чуть, поэтому высылаю второей задание.

**Общая формулировка**
Разработать консольную утилиту, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**transpose**
“Транспонирует” входной текст по входящим в него словам, разделённым последовательностями пробелов, т.е. если входящий файл содержал строки “A    B C” и “D E”, то результатом будет файл со строками “A D”, “B E” и “C”.

file задаёт имя входного файла. Если параметр отсутствует, следует считывать текст с консоли.
- Флаг -o ofile  задаёт имя выходного файла. Если параметр отсутствует, следует выводить результаты на консоль.
- Флаг -a num означает, что в выходном тексте каждое слово должно занимать num символов, а оставшееся место (если оно есть) должно быть заполнено пробелами.
- Флаг -t означает, что если слово “не влезает” в выделенное для него место (флагом -а), то его следует обрезать до нужного размера.
- Флаг -r означает, что слово в рамках выделенного для него места (флагом -а) следует выравнивать по правой границе. Если данный флаг не указан, слово выравнивается по левой границе.

Command line: transpose [-a num] [-t] [-r] [-o ofile] [file]

В случае, когда какое-нибудь из имён файлов указано неверно, следует выдать ошибку. В случае, если флаг -а отсутствует, но присутствуют флаги -t или -r, следует выравнивать текст так, будто указан флаг “-а 10”.

Кроме самой программы, следует написать автоматические тесты к ней.

Также необходимо разработать скрипты и/или инструкции сборки приложения и его запуска из командной строки. 

**P.S.** Проверка второго задания начинается не раньше исправления всех замечания к первому заданию. В любом случае напишите в комментариях к этому issue, когда задание будет готово к проверке.

**P.S.S.** Если будете делать это задание в другом репозитории, дайте ссылку в комментариях к этому issue.

**Comment by JohnKhandygo** [comment]
Рекомендуется следующий подход к разработке:
1. Реализовать класс со всей необходимой логикой так, как Вы это делали в предыдущем задании (с покрытием тестами и прочим). Другими словами, забудьте на время, что Ваше приложение должно работать из консоли.
2. Отдельно написать "обертку", которая будет парсить аргументы командной строки (используя библотеку) и вызывать разработанные на первом этапе методы. Скорее всего то, что будет написано на данном этапе даже не потребуется покрывать тестами, поскольку функциональность сторонних библотек обычно не тестируется (либо тестируется в каких-то очень сложных случаях). 

Собственно после готовности первого этапа можно начинать проверку.

**Comment by JohnKhandygo** [comment]
Первое задание зачтено.

**Comment by leonid135** [comment]
Здравствуйте , задание готово к проверке . С уважением , Зимин леонид

**Comment by leonid135** [comment]
Можно получить третье задание ?

**Comment by JohnKhandygo** [comment]
Нет, я еще ни разу не проверял Ваше второе задание. О третьем не может быть и речи.

**Comment by leonid135** [comment]
Иначе я просто не успею сделать ничего по 3 заданию к воскресенью . Вы же можете не проверять третье пока я не доделаю второе до нужного уровня

**Comment by JohnKhandygo** [comment]
У Вас была достаточно времени для того, что сделать второе задание и получить третье вовремя.

**Comment by leonid135** [comment]
Да , я понимаю , но почему бы не улучшить положение... Пока вы будуте проверять я успею что-либо сделать . Это разве создаёт нам какую-то проблему ?

**Comment by JohnKhandygo** [comment]
Все были в одинаковом положении. Я могу выдать третье задание, но тогда без исправлений по второму: я его просто проверю и поставлю оценку. Так Вас устраивает?

**Comment by leonid135** [comment]
Если оценка получится хотя бы 3 , то вполне устроит .

**Comment by JohnKhandygo** [comment]
Вы либо соглашаетесь и получаете третье задание, либо не соглашаетесь и будете делать исправления, если таковые будут.

**Comment by leonid135** [comment]
Хорошо , согласен получить 3 без исправлений 2

**Comment by JohnKhandygo** [comment]
Окей

**Comment by JohnKhandygo** [comment]
По второму заданию (из существенного):
- **Код (даже после добавления зависимостей на junit и commons-cli) не компилируется.** 
- По условию задания:
  > Также необходимо разработать скрипты и/или инструкции сборки приложения и его запуска из командной строки.
  Я у Вас ни инструкций, ни скриптов не вижу.
- Некорректно реализовано чтение из командной строки и файла: не понятно, с чего бы пустые строки должны игнорироваться.
- Некорректный вывод программы в случае, когда существует строка `l1`, за которой следует строка `l2` такая что `l1.length() < l2.length()`.

За некомпилирующийся код 2, -0.5 штрафа за последнюю аттестацию. Итого, второе задание зачтено на 1.5 балла.

**Comment by leonid135** [comment]
Существенное я могу исправить ?

**Comment by JohnKhandygo** [comment]
Вы отказались от возможности исправить что-либо по второму заданию в пользу третьего.
