### ISSUE TITLE
Task 3.0

### ISSUE THREAD

**Issue by JohnKhandygo** [leonid135/orientedGraph#3]
**Общая формулировка**
Разработать программу с графическим интерфейсом, реализующую указанную в задании функциональность, на языках Java и/или Kotlin. При проектировании использовать объектно-ориентированный подход. Разработать автоматические тесты для отдельных частей программы. Написанный код держать в отдельном проекте или модуле в репозитории на GitHub.

**Английские шашки**
Реализовать игру Английские шашки для двух игроков за одним компьютером, с графическим интерфейсом. Реализовать все правила игры и проверить их работоспособность тестами. Правила [здесь](https://ru.wikipedia.org/wiki/Английские_шашки).

**Comment by leonid135** [comment]
https://github.com/leonid135/EnglishDraughts

Репозиторий с 3 заданием

**Comment by JohnKhandygo** [comment]
Перенес описание задания в новый репозиторий, все замечания будут появляться там.
